# Generated by Django 4.2.2 on 2023-09-28 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snsapp", "0004_user_usertype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="userType",
            new_name="usertype",
        ),
    ]
