# Generated by Django 4.2.2 on 2023-09-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snsapp", "0005_rename_usertype_user_usertype"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="divinertype",
            field=models.CharField(
                choices=[("命術", "命術"), ("卜術", "卜術"), ("相術", "相術")],
                default="命術",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
