# Generated by Django 4.2.2 on 2023-09-30 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("snsapp", "0007_alter_user_divinertype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("stripe_product_id", models.CharField(max_length=100)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="product_files/"),
                ),
                ("url", models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="divinertype",
            field=models.CharField(
                choices=[
                    ("命術_四柱推命", "命術_四柱推命"),
                    ("命術_紫微斗数", "命術_紫微斗数"),
                    ("命術_風水", "命術_風水"),
                    ("卜術_易経", "卜術_易経"),
                    ("卜術_タロット", "卜術_タロット"),
                    ("卜術_ルーン", "卜術_ルーン"),
                    ("卜術_オーラ", "卜術_オーラ"),
                    ("卜術_ペンデュラム", "卜術_ペンデュラム"),
                    ("相術_手相", "相術_手相"),
                    ("相術_顔相", "相術_顔相"),
                    ("相術_人相", "相術_人相"),
                    ("相術_波動", "相術_波動"),
                    ("霊感_オラクルカード", "霊感_オラクルカード"),
                    ("霊感_クレアボヤント", "霊感_クレアボヤント"),
                    ("霊感_透視", "霊感_透視"),
                    ("霊感_オーラリーディング", "霊感_オーラリーディング"),
                    ("心理_心理学", "心理_心理学"),
                    ("心理_占星術", "心理_占星術"),
                    ("心理_動物占い", "心理_動物占い"),
                    ("数秘術", "数秘術"),
                    ("ドリームリーディング", "ドリームリーディング"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_price_id", models.CharField(max_length=100)),
                ("price", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Prices",
                        to="snsapp.product",
                    ),
                ),
            ],
        ),
    ]
