# Generated by Django 4.2.2 on 2023-09-30 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snsapp", "0008_product_alter_user_divinertype_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Price",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
