# Generated by Django 4.2.2 on 2023-10-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snsapp", "0009_delete_price_delete_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="DivinerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("命術_四柱推命", "命術_四柱推命"),
                            ("命術_紫微斗数", "命術_紫微斗数"),
                            ("命術_風水", "命術_風水"),
                            ("卜術_易経", "卜術_易経"),
                            ("卜術_タロット", "卜術_タロット"),
                            ("卜術_ルーン", "卜術_ルーン"),
                            ("卜術_オーラ", "卜術_オーラ"),
                            ("卜術_ペンデュラム", "卜術_ペンデュラム"),
                            ("相術_手相", "相術_手相"),
                            ("相術_顔相", "相術_顔相"),
                            ("相術_人相", "相術_人相"),
                            ("相術_波動", "相術_波動"),
                            ("霊感_オラクルカード", "霊感_オラクルカード"),
                            ("霊感_クレアボヤント", "霊感_クレアボヤント"),
                            ("霊感_透視", "霊感_透視"),
                            ("霊感_オーラリーディング", "霊感_オーラリーディング"),
                            ("心理_心理学", "心理_心理学"),
                            ("心理_占星術", "心理_占星術"),
                            ("心理_動物占い", "心理_動物占い"),
                            ("数秘術", "数秘術"),
                            ("ドリームリーディング", "ドリームリーディング"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="divinertype",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.AddField(
            model_name="user",
            name="divinertype",
            field=models.ManyToManyField(to="snsapp.divinertype"),
        ),
    ]
