# Generated by Django 4.2.2 on 2023-10-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snsapp", "0010_divinertype_remove_user_divinertype_delete_post_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="point",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="divinertype",
            name="name",
            field=models.CharField(
                choices=[
                    (11, "命術_四柱推命"),
                    (12, "命術_紫微斗数"),
                    (13, "命術_風水"),
                    (21, "卜術_易経"),
                    (22, "卜術_タロット"),
                    (23, "卜術_ルーン"),
                    (24, "卜術_オーラ"),
                    (25, "卜術_ペンデュラム"),
                    (31, "相術_手相"),
                    (32, "相術_顔相"),
                    (33, "相術_人相"),
                    (34, "相術_波動"),
                    (41, "霊感_オラクルカード"),
                    (42, "霊感_クレアボヤント"),
                    (43, "霊感_透視"),
                    (44, "霊感_オーラリーディング"),
                    (51, "心理_心理学"),
                    (52, "心理_占星術"),
                    (53, "心理_動物占い"),
                    (61, "数秘術"),
                    (71, "ドリームリーディング"),
                ],
                max_length=30,
            ),
        ),
    ]
