# Generated by Django 4.2.2 on 2023-10-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snsapp", "0012_alter_user_divinertype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("send", "send mesasge"),
                            ("divination", "send divination"),
                        ],
                        max_length=30,
                    ),
                ),
                ("point", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
