# Generated by Django 4.2.2 on 2023-10-20 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("snsapp", "0013_cost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="point",
            new_name="points",
        ),
    ]
