# Generated by Django 4.2.2 on 2023-10-30 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("snsapp", "0014_rename_point_user_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="userPro",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
