# Generated by Django 4.2.2 on 2023-12-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snsapp", "0015_alter_profile_userpro"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="receiver_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="messages",
            name="sender_id",
            field=models.IntegerField(default=0),
        ),
    ]
