# Generated by Django 4.2.2 on 2024-02-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snsapp", "0019_alter_config_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="value",
            field=models.TextField(),
        ),
    ]
