# Generated by Django 4.2.2 on 2024-02-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snsapp", "0020_alter_config_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="introduction",
            field=models.TextField(blank=True, null=True),
        ),
    ]
