# Generated by Django 4.2.2 on 2023-09-16 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0002_alter_customuser_area_alter_customuser_industry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="サイト名")),
            ],
        ),
        migrations.RemoveField(
            model_name="comment",
            name="area",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="site",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="area",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="trade_name",
        ),
        migrations.DeleteModel(
            name="Area",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Industry",
        ),
        migrations.DeleteModel(
            name="Site",
        ),
        migrations.AddField(
            model_name="customuser",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="review.category",
            ),
        ),
    ]
