# Generated by Django 4.2.2 on 2023-10-01 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopping", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="url",
        ),
    ]
